### PR TITLE
add tests for APK module

### PR DESCRIPTION
**Pull request by frennkie**
Create initial tests for APK module. Sample .apk file is just a simple
hello world app that I wrote. The dump option fails and I assume this is
a Python3 issue. Needs to be checked further.

### CODE REVIEW

**Comment by frennkie** [comment]
This is the traceback on the dump option

```
TypeError                                 Traceback (most recent call last)
<ipython-input-21-2fe61b5a5821> in <module>()
----> 1 a.run()

/home/user/work/viper/viper/modules/apk.py in run(self)
    197         if self.args.dump is not None:
    198             self.log('info', "Decompiling Code")
--> 199             andro_dump(vm, vmx, self.args.dump)
    200             self.log('info', "Decompiled code saved to {0}".format(self.args.dump))
    201         elif self.args.info:

/home/user/work/viper/viper/modules/apk.py in andro_dump(vm, vmx, dump_path)
    139                     continue
    140                 ms = DvMethod(mx)
--> 141                 ms.process()
    142                 with open(dump_path, 'a+') as outfile:
    143                     outfile.write(str(method.get_class_name()))

/home/user/work/androguard/androguard/decompiler/dad/decompile.py in process(self, doAST)
    138             return
    139
--> 140         graph = construct(self.start_block, self.var_to_name, self.exceptions)
    141         self.graph = graph
    142

/home/user/work/androguard/androguard/decompiler/dad/graph.py in construct(start_block, vmap, exceptions)
    465
    466     for block in bfs_blocks:
--> 467         node = make_node(graph, block, block_to_node, vmap, gen_ret)
    468         graph.add_node(node)
    469

/home/user/work/androguard/androguard/decompiler/dad/graph.py in make_node(graph, block, block_to_node, vmap, gen_ret)
    410     node = block_to_node.get(block)
    411     if node is None:
--> 412         node = build_node_from_block(block, vmap, gen_ret)
    413         block_to_node[block] = node
    414     if block.exception_analysis:

/home/user/work/androguard/androguard/decompiler/dad/basic_blocks.py in build_node_from_block(block, vmap, gen_ret, exception_type)
    357             continue
    358         else:
--> 359             lins.append(_ins(ins, vmap))
    360         idx += ins.get_length()
    361     name = block.get_name()

/home/user/work/androguard/androguard/decompiler/dad/opcode_ins.py in constwidehigh16(ins, vmap)
    286 def constwidehigh16(ins, vmap):
    287     logger.debug('ConstWideHigh16 : %s', ins.get_output())
--> 288     value = unpack('=d', '\x00\x00\x00\x00\x00\x00' + pack('=h', ins.BBBB))[0]
    289     cst = Constant(value, 'D', ins.BBBB)
    290     return assign_const(ins.AA, cst, vmap)

TypeError: Can't convert 'bytes' object to str implicitly
```

As far as I see it that's nothing we can fix in Viper  - ~so we need to open an issue on https://github.com/androguard/androguard, right?~

Update: There already is an open PR for this: androguard/androguard#228

**Comment by Rafiot** [comment]
What I did with the other 3rd party modules that are broken in python3 was to fork the repo under viper-framework org, merge the required patches and use the that version in the requirement file of viper.

We can give it a few days, but if this PR isn't merged upstream, let me know.

**Comment by Rafiot** [comment]
@frennkie no rush, but can you fix the conflict here?

**Comment by Rafiot** [comment]
Thank you :)

**Comment by frennkie** [comment]
Whoops.. just accidentally deleted all branches (including the ones with open PRs..) /o\

**Comment by Rafiot** [comment]
merged :)

**Pull request closed without merging**
